__name__ = "product-inventory-management-system"
__version__ = "1.0"
__url__ = "https://github.com/NSBM-SPM-2021/github-basics-buddhiwickramanayaka/tree/main/Product-inventory-management-system"
__author__ = "Buddhi Wickramanayake"
__email__ = "buddhiwickramanayaka6@gmail.com"
__description__ = "Product Inventory Management System powered by Flask"
__license__ = "MIT"
